/**
 * Local persistence layer.
 *
 * Everything the app remembers between visits goes through this module. When a
 * real backend arrives, only the bodies of these functions change — callers keep
 * the same signatures.
 *
 * All reads are SSR-safe: they return `null`/defaults when `window` is absent.
 */
import type { UserProfile } from "./types";

const KEYS = {
  profile: "borderless.profile",
  completedActions: "borderless.completedActions",
  dismissedOpportunities: "borderless.dismissedOpportunities",
} as const;

function read<T>(key: string): T | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = window.localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : null;
  } catch {
    return null;
  }
}

function write(key: string, value: unknown): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(key, JSON.stringify(value));
  } catch {
    /* quota or private mode — the app still works, it just forgets */
  }
}

function remove(key: string): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.removeItem(key);
  } catch {
    /* ignore */
  }
}

/* -------------------------------- profile -------------------------------- */

export function loadProfile(): UserProfile | null {
  return read<UserProfile>(KEYS.profile);
}

export function saveProfile(profile: UserProfile): UserProfile {
  const now = new Date().toISOString();
  const stored: UserProfile = {
    ...profile,
    createdAt: profile.createdAt ?? now,
    updatedAt: now,
  };
  write(KEYS.profile, stored);
  return stored;
}

export function clearProfile(): void {
  remove(KEYS.profile);
}

/* ---------------------------- action completion --------------------------- */

/** Completion is stored separately from the actions themselves, because the
 *  actions are regenerated by the rule engine on every load. */
export function loadCompletedActionIds(): string[] {
  return read<string[]>(KEYS.completedActions) ?? [];
}

export function saveCompletedActionIds(ids: string[]): void {
  write(KEYS.completedActions, Array.from(new Set(ids)));
}

/* ------------------------------ opportunities ----------------------------- */

export function loadDismissedOpportunityIds(): string[] {
  return read<string[]>(KEYS.dismissedOpportunities) ?? [];
}

export function saveDismissedOpportunityIds(ids: string[]): void {
  write(KEYS.dismissedOpportunities, Array.from(new Set(ids)));
}

/* --------------------------------- reset ---------------------------------- */

export function clearAll(): void {
  Object.values(KEYS).forEach(remove);
}

export const STORAGE_KEYS = KEYS;
