"use client";

/**
 * Action list with persisted completion state.
 *
 * Actions themselves are regenerated by the rule engine on every load, so only
 * the set of completed ids is stored.
 */
import { useCallback, useEffect, useMemo, useState } from "react";

import { deriveActions } from "@/lib/rules";
import { loadCompletedActionIds, saveCompletedActionIds } from "@/lib/storage";
import type { Action, Impact } from "@/lib/types";

export interface UseActionsResult {
  actions: Action[];
  open: Action[];
  done: Action[];
  toggle: (id: string) => void;
  ready: boolean;
}

export function useActions(impacts: Impact[]): UseActionsResult {
  const [completedIds, setCompletedIds] = useState<string[]>([]);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    setCompletedIds(loadCompletedActionIds());
    setReady(true);
  }, []);

  const toggle = useCallback((id: string) => {
    setCompletedIds((prev) => {
      const next = prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id];
      saveCompletedActionIds(next);
      return next;
    });
  }, []);

  const actions = useMemo(
    () => deriveActions(impacts).map((a) => ({ ...a, completed: completedIds.includes(a.id) })),
    [impacts, completedIds],
  );

  return {
    actions,
    open: actions.filter((a) => !a.completed),
    done: actions.filter((a) => a.completed),
    toggle,
    ready,
  };
}
